### ISSUE TITLE
有些格式不能识别

### ISSUE THREAD

**Issue by lvxianchao** [pupuk/address#2]
收货人: 杨燕艳
手机号码: 13111111111
所在地区: 广东省深圳市龙岗区龙岗街道
详细地址: 格水村三巷十号三楼

像这种格式识别不了，希望能做得更强大一些。

**Comment by pupuk** [comment]
![image](https://user-images.githubusercontent.com/7934974/83862291-4ed69a80-a754-11ea-991b-0316fa211456.png)
![image](https://user-images.githubusercontent.com/7934974/83862310-572ed580-a754-11ea-99b6-32f9512ca4bd.png)

刚才改了一下，已经可以了。麻烦帮忙star一下项目，谢谢
