### ISSUE TITLE
无法获取 [province] => [city] => [region] =>

### ISSUE THREAD

**Issue by bxs17** [pupuk/address#4]
Array ( [idn] => 120113196808214821 [mobile] => 13800138000 [postcode] => 518000 [name] => 张三 [addr] => 深圳市龙华区龙华街道1980科技文化产业园3栋317 [province] => [city] => [region] => [street] => 值�1980科技文化产业园3栋317 )

**Comment by pupuk** [comment]
![image](https://user-images.githubusercontent.com/7934974/116672531-e2e8ca80-a9d4-11eb-9385-9b0142986dba.png)
![image](https://user-images.githubusercontent.com/7934974/116672551-ea0fd880-a9d4-11eb-8ab0-555e84c93974.png)

应该是PHP版本，以及文件字符集的问题，建议使用PHP7+，代码文件格式使用uft8, 无bom
